export const translations = {
  en: {
    welcome: "Welcome",
    tagline: "Predictive Agricultural Marketplace",
    farmer: "Farmer",
    buyer: "Institutional Buyer",
    harvest_advice: "AI Harvest Advice",
    predicted_price: "Predicted Price",
    market_sentiment: "Market Sentiment",
    harvest_now: "Harvest Now",
    wait_days: "Wait {days} Days",
    place_bid: "Place Bid",
    mandi_prices: "Mandi Prices",
    my_bids: "My Bids",
    dashboard: "Dashboard",
    best_offer: "Best Offer",
    total_bids: "Total Bids",
    ai_price_prediction: "AI Price Prediction",
    smart_recommendation: "Smart Recommendation",
    hold_price_rise: "Hold - Price will rise in 2 days",
    demand_factor: "Demand factor",
    rain_probability: "Rain probability",
    seven_day_trend: "7-Day Price Trend",
    my_crop_listings: "My Crop Listings",
    rain_alert: "Rain alert: Consider harvesting {crop} today",
    live: "Live",
    active_crops: "Active Crops",
    pending_bids: "Pending Bids",
    voice_assistant: "Voice Assistant",
    listening: "Listening...",
    ask_me: "Ask me about prices or harvest timing",
    harvest_today: "Harvest Today",
    wait_2_days: "Wait 2 Days",
    rain_risk: "Rain Risk",
    logistics: "Logistics Availability",
    nearby_buyers: "Nearby Buyers",
    est_delivery: "Est. Delivery Time",
    mandi_price: "Current Mandi Price",
    historical_trend: "Historical Trend",
    marketplace: "Marketplace",
    market_intelligence: "Market Intelligence",
    ai_plans: "AI Harvest Plans",
    start_query: "Start Query",
    stop_ai: "Stop AI",
    speak_now: "Speak now...",
    location: "Location",
    name: "Name",
    role: "Role",
    email: "Email",
    save_profile: "Save Profile",
    select_role: "Select Role",
    enter_name: "Enter your name",
    enter_location: "Enter your location",
    active_bids: "Active Bids",
    total_revenue: "Total Revenue",
    active_orders: "Active Orders",
    listening_ai: "Listening...",
    logout: "Logout",
    bids: "Bids",
    daily: "Daily",
    weekly: "Weekly",
    company: "Company",
    sponsor: "Sponsor",
    market_insights: "Market Insights",
    real_time_mandi: "Real-time Mandi Prices",
    timeframe: "Timeframe",
    bid_history: "Bid History",
    no_crops: "No crops listed yet. Start by adding your first harvest.",
    view_ai_plan: "View AI Plan",
    kg_available: "kg available",
    marketplace_empty: "Marketplace is currently empty. Check back later!",
    bid_placed: "Bid Placed",
    bid_amount_placeholder: "Bid amount per kg",
    list_new_crop: "List New Crop",
    list_your_crop: "List your crop",
    crop_type: "Crop Type",
    quantity_kg: "Quantity (kg)",
    est_harvest: "Est. Harvest",
    cancel: "Cancel",
    list_crop: "List Crop",
    crop_type_placeholder: "e.g. Organic Tomatoes",
    quantity_placeholder: "500",
    location_placeholder: "e.g. Vellore, Tamil Nadu",
    humidity: "Humidity",
    wind: "Wind",
    ai_forecast: "AI Forecast",
    system_healthy: "System Healthy",
    system_degraded: "System Degraded",
    retry_check: "Retry System Check",
    details: "Details",
    something_went_wrong: "Something went wrong",
    reload_app: "Reload Application",
    enter_location_placeholder: "Enter location (e.g. Chennai)",
    tomato: "Tomato",
    wheat: "Wheat",
    rice: "Rice",
    corn: "Corn",
    potato: "Potato",
    onion: "Onion",
    vellore: "Vellore",
    chennai: "Chennai",
    nashik: "Nashik",
    growing: "Growing",
    ready: "Ready to Harvest",
    harvested: "Harvested",
    vellore_market: "Vellore Market",
    nashik_market: "Nashik Market",
    sugarcane: "Sugarcane",
    turmeric: "Turmeric",
    banana: "Banana",
    cotton: "Cotton",
    coconut: "Coconut",
    mango: "Mango",
    coffee: "Coffee",
    tea: "Tea",
    rubber: "Rubber",
    cardamom: "Cardamom",
    pepper: "Pepper",
    ginger: "Ginger",
    garlic: "Garlic",
    chili: "Chili",
    groundnut: "Groundnut",
    sunflower: "Sunflower",
    mustard: "Mustard",
    soybean: "Soybean",
    jute: "Jute",
    tobacco: "Tobacco",
    "moong dal": "Moong Dal",
    "urad dal": "Urad Dal",
    "arhar dal": "Arhar Dal",
    gram: "Gram",
    jowar: "Jowar",
    bajra: "Bajra",
    ragi: "Ragi",
    barley: "Barley",
    sesame: "Sesame",
    castor: "Castor",
    grapes: "Grapes",
    guava: "Guava",
    papaya: "Papaya",
    pomegranate: "Pomegranate",
    apple: "Apple",
    orange: "Orange",
    coimbatore: "Coimbatore",
    madurai: "Madurai",
    trichy: "Trichy",
    pune: "Pune",
    nagpur: "Nagpur",
    kanyakumari: "Kanyakumari",
    erode: "Erode",
    ariyalur: "Ariyalur",
    chengalpattu: "Chengalpattu",
    cuddalore: "Cuddalore",
    dharmapuri: "Dharmapuri",
    dindigul: "Dindigul",
    kallakurichi: "Kallakurichi",
    kancheepuram: "Kancheepuram",
    karur: "Karur",
    krishnagiri: "Krishnagiri",
    mayiladuthurai: "Mayiladuthurai",
    nagapattinam: "Nagapattinam",
    namakkal: "Namakkal",
    nilgiris: "Nilgiris",
    perambalur: "Perambalur",
    pudukkottai: "Pudukkottai",
    ramanathapuram: "Ramanathapuram",
    ranipet: "Ranipet",
    salem: "Salem",
    sivaganga: "Sivaganga",
    tenkasi: "Tenkasi",
    thanjavur: "Thanjavur",
    theni: "Theni",
    thoothukudi: "Thoothukudi",
    tiruchirappalli: "Tiruchirappalli",
    tirunelveli: "Tirunelveli",
    tirupathur: "Tirupathur",
    tiruppur: "Tiruppur",
    tiruvallur: "Tiruvallur",
    tiruvannamalai: "Tiruvannamalai",
    tiruvarur: "Tiruvarur",
    viluppuram: "Viluppuram",
    virudhunagar: "Virudhunagar",
    mumbai: "Mumbai",
    delhi: "Delhi",
    bangalore: "Bangalore",
    hyderabad: "Hyderabad",
    ahmedabad: "Ahmedabad",
    kolkata: "Kolkata",
    surat: "Surat",
    jaipur: "Jaipur",
    lucknow: "Lucknow",
    kanpur: "Kanpur",
    indore: "Indore",
    thane: "Thane",
    bhopal: "Bhopal",
    visakhapatnam: "Visakhapatnam",
    patna: "Patna",
    vadodara: "Vadodara",
    ghaziabad: "Ghaziabad",
    ludhiana: "Ludhiana",
    agra: "Agra",
    faridabad: "Faridabad",
    meerut: "Meerut",
    rajkot: "Rajkot",
    varanasi: "Varanasi",
    srinagar: "Srinagar",
    aurangabad: "Aurangabad",
    dhanbad: "Dhanbad",
    amritsar: "Amritsar",
    allahabad: "Allahabad",
    howrah: "Howrah",
    ranchi: "Ranchi",
    gwalior: "Gwalior",
    jabalpur: "Jabalpur",
    vijayawada: "Vijayawada",
    jodhpur: "Jodhpur",
    raipur: "Raipur",
    kota: "Kota",
    guwahati: "Guwahati",
    chandigarh: "Chandigarh",
    solapur: "Solapur",
    bareilly: "Bareilly",
    moradabad: "Moradabad",
    mysore: "Mysore",
    gurgaon: "Gurgaon",
    aligarh: "Aligarh",
    jalandhar: "Jalandhar",
    bhubaneswar: "Bhubaneswar",
    thiruvananthapuram: "Thiruvananthapuram",
    bhiwandi: "Bhiwandi",
    saharanpur: "Saharanpur",
    amravati: "Amravati",
    bikaner: "Bikaner",
    noida: "Noida",
    jamshedpur: "Jamshedpur",
    bhilai: "Bhilai",
    cuttack: "Cuttack",
    firozabad: "Firozabad",
    kochi: "Kochi",
    nellore: "Nellore",
    bhavnagar: "Bhavnagar",
    dehradun: "Dehradun",
    durgapur: "Durgapur",
    asansol: "Asansol",
    rourkela: "Rourkela",
    nanded: "Nanded",
    kolhapur: "Kolhapur",
    ajmer: "Ajmer",
    akola: "Akola",
    gulbarga: "Gulbarga",
    jamnagar: "Jamnagar",
    ujjain: "Ujjain",
    loni: "Loni",
    siliguri: "Siliguri",
    jhansi: "Jhansi",
    ulhasnagar: "Ulhasnagar",
    jammu: "Jammu",
    sangli: "Sangli",
    mangalore: "Mangalore",
    belgaum: "Belgaum",
    gaya: "Gaya",
    jalgaon: "Jalgaon",
    udaipur: "Udaipur",
    shimla: "Shimla",
    panaji: "Panaji",
    imphal: "Imphal",
    agartala: "Agartala",
    aizawl: "Aizawl",
    kohima: "Kohima",
    shillong: "Shillong",
    itanagar: "Itanagar",
    gangtok: "Gangtok",
    pondicherry: "Pondicherry",
    leh: "Leh",
    "port blair": "Port Blair",
    silvassa: "Silvassa",
    daman: "Daman",
    kavaratti: "Kavaratti",
  },
  ta: {
    welcome: "வரவேற்கிறோம்",
    tagline: "முன்கணிப்பு விவசாய சந்தை",
    farmer: "விவசாயி",
    buyer: "நிறுவன வாங்குபவர்",
    harvest_advice: "AI அறுவடை ஆலோசனை",
    predicted_price: "கணிக்கப்பட்ட விலை",
    market_sentiment: "சந்தை உணர்வு",
    harvest_now: "இப்போதே அறுவடை செய்யுங்கள்",
    wait_days: "{days} நாட்கள் காத்திருக்கவும்",
    place_bid: "ஏலம் விடுங்கள்",
    mandi_prices: "மண்டி விலைகள்",
    my_bids: "எனது ஏலங்கள்",
    dashboard: "டாஷ்போர்டு",
    best_offer: "சிறந்த சலுகை",
    total_bids: "மொத்த ஏலங்கள்",
    ai_price_prediction: "AI விலை கணிப்பு",
    smart_recommendation: "ஸ்மார்ட் பரிந்துரை",
    hold_price_rise: "பிடி - 2 நாட்களில் விலை உயரும்",
    demand_factor: "தேவை காரணி",
    rain_probability: "மழை நிகழ்தகவு",
    seven_day_trend: "7-நாள் விலை போக்கு",
    my_crop_listings: "எனது பயிர் பட்டியல்கள்",
    rain_alert: "மழை எச்சரிக்கை: இன்று {crop} அறுவடை செய்வதைக் கருத்தில் கொள்ளுங்கள்",
    live: "நேரலை",
    active_crops: "செயலில் உள்ள பயிர்கள்",
    pending_bids: "நிலுவையில் உள்ள ஏலங்கள்",
    voice_assistant: "குரல் உதவியாளர்",
    listening: "கேட்கிறது...",
    ask_me: "விலை அல்லது அறுவடை நேரம் பற்றி என்னிடம் கேளுங்கள்",
    harvest_today: "இன்று அறுவடை செய்யுங்கள்",
    wait_2_days: "2 நாட்கள் காத்திருக்கவும்",
    rain_risk: "மழை ஆபத்து",
    logistics: "தளவாடங்கள் கிடைக்கும் தன்மை",
    nearby_buyers: "அருகிலுள்ள வாங்குபவர்கள்",
    est_delivery: "மதிப்பிடப்பட்ட விநியோக நேரம்",
    mandi_price: "தற்போதைய மண்டி விலை",
    historical_trend: "வரலாற்று போக்கு",
    marketplace: "சந்தை",
    market_intelligence: "சந்தை நுண்ணறிவு",
    ai_plans: "AI அறுவடை திட்டங்கள்",
    start_query: "கேள்வியைத் தொடங்கு",
    stop_ai: "AI ஐ நிறுத்து",
    speak_now: "இப்போது பேசுங்கள்...",
    location: "இடம்",
    name: "பெயர்",
    role: "பங்கு",
    email: "மின்னஞ்சல்",
    save_profile: "சுயவிவரத்தைச் சேமி",
    select_role: "பங்கினைத் தேர்ந்தெடுக்கவும்",
    enter_name: "உங்கள் பெயரை உள்ளிடவும்",
    enter_location: "உங்கள் இடத்தை உள்ளிடவும்",
    active_bids: "செயலில் உள்ள ஏலங்கள்",
    total_revenue: "மொத்த வருவாய்",
    active_orders: "செயலில் உள்ள ஆர்டர்கள்",
    listening_ai: "கேட்கிறது...",
    logout: "வெளியேறு",
    bids: "ஏலங்கள்",
    daily: "தினசரி",
    weekly: "வாராந்திர",
    company: "நிறுவனம்",
    sponsor: "ஸ்பான்சர்",
    market_insights: "சந்தை நுண்ணறிவு",
    real_time_mandi: "நேரலை மண்டி விலைகள்",
    timeframe: "கால அளவு",
    bid_history: "ஏல வரலாறு",
    no_crops: "பயிர்கள் இன்னும் பட்டியலிடப்படவில்லை. உங்கள் முதல் அறுவடையைச் சேர்ப்பதன் மூலம் தொடங்கவும்.",
    view_ai_plan: "AI திட்டத்தைப் பார்க்கவும்",
    kg_available: "கிலோ கிடைக்கிறது",
    marketplace_empty: "சந்தை தற்போது காலியாக உள்ளது. பின்னர் சரிபார்க்கவும்!",
    bid_placed: "ஏலம் வைக்கப்பட்டது",
    bid_amount_placeholder: "ஒரு கிலோவிற்கு ஏலத் தொகை",
    list_new_crop: "புதிய பயிரைப் பட்டியலிடுங்கள்",
    list_your_crop: "உங்கள் பயிரைப் பட்டியலிடுங்கள்",
    crop_type: "பயிர் வகை",
    quantity_kg: "அளவு (கிலோ)",
    est_harvest: "மதிப்பிடப்பட்ட அறுவடை",
    cancel: "ரத்துசெய்",
    list_crop: "பயிரைப் பட்டியலிடு",
    crop_type_placeholder: "எ.கா. ஆர்கானிக் தக்காளி",
    quantity_placeholder: "500",
    location_placeholder: "எ.கா. வேலூர், தமிழ்நாடு",
    humidity: "ஈரப்பதம்",
    wind: "காற்று",
    ai_forecast: "AI முன்னறிவிப்பு",
    system_healthy: "அமைப்பு ஆரோக்கியமானது",
    system_degraded: "அமைப்பு குறைந்துள்ளது",
    retry_check: "மீண்டும் சரிபார்க்கவும்",
    details: "விவரங்கள்",
    something_went_wrong: "ஏதோ தவறு நடந்துவிட்டது",
    reload_app: "பயன்பாட்டை மீண்டும் ஏற்றவும்",
    enter_location_placeholder: "இடத்தை உள்ளிடவும் (எ.கா. சென்னை)",
    tomato: "தக்காளி",
    wheat: "கோதுமை",
    rice: "அரிசி",
    corn: "சோளம்",
    potato: "உருளைக்கிழங்கு",
    onion: "வெங்காயம்",
    vellore: "வேலூர்",
    chennai: "சென்னை",
    nashik: "நாசிக்",
    growing: "வளர்கிறது",
    ready: "அறுவடைக்கு தயார்",
    harvested: "அறுவடை செய்யப்பட்டது",
    vellore_market: "வேலூர் சந்தை",
    nashik_market: "நாசிக் சந்தை",
    sugarcane: "கரும்பு",
    turmeric: "மஞ்சள்",
    banana: "வாழை",
    cotton: "பருத்தி",
    coconut: "தேங்காய்",
    mango: "மாம்பழம்",
    coffee: "காபி",
    tea: "தேநீர்",
    rubber: "ரப்பர்",
    cardamom: "ஏலக்காய்",
    pepper: "மிளகு",
    ginger: "இஞ்சி",
    garlic: "பூண்டு",
    chili: "மிளகாய்",
    groundnut: "நிலக்கடலை",
    sunflower: "சூரியகாந்தி",
    mustard: "கடுகு",
    soybean: "சோயாபீன்",
    jute: "சணல்",
    tobacco: "புகையிலை",
    "moong dal": "பாசிப்பருப்பு",
    "urad dal": "உளுத்தம் பருப்பு",
    "arhar dal": "துவரம் பருப்பு",
    gram: "கடலை",
    jowar: "சோளம் (ஜோவர்)",
    bajra: "கம்பு",
    ragi: "கேழ்வரகு",
    barley: "பார்லி",
    sesame: "எள்",
    castor: "ஆமணக்கு",
    grapes: "திராட்சை",
    guava: "கொய்யா",
    papaya: "பப்பாளி",
    pomegranate: "மாதுளை",
    apple: "ஆப்பிள்",
    orange: "ஆரஞ்சு",
    coimbatore: "கோயம்புத்தூர்",
    madurai: "மதுரை",
    trichy: "திருச்சி",
    pune: "புனே",
    nagpur: "நாக்பூர்",
    kanyakumari: "கன்னியாகுமரி",
    erode: "ஈரோடு",
    ariyalur: "அரியலூர்",
    chengalpattu: "செங்கல்பட்டு",
    cuddalore: "கடலூர்",
    dharmapuri: "தர்மபுரி",
    dindigul: "திண்டுக்கல்",
    kallakurichi: "கள்ளக்குறிச்சி",
    kancheepuram: "காஞ்சிபுரம்",
    karur: "கரூர்",
    krishnagiri: "கிருஷ்ணகிரி",
    mayiladuthurai: "மயிலாடுதுறை",
    nagapattinam: "நாகப்பட்டினம்",
    namakkal: "நாமக்கல்",
    nilgiris: "நீலகிரி",
    perambalur: "பெரம்பலூர்",
    pudukkottai: "புதுக்கோட்டை",
    ramanathapuram: "இராமநாதபுரம்",
    ranipet: "ராணிப்பேட்டை",
    salem: "சேலம்",
    sivaganga: "சிவகாசி",
    tenkasi: "தென்காசி",
    thanjavur: "தஞ்சாவூர்",
    theni: "தேனி",
    thoothukudi: "தூத்துக்குடி",
    tiruchirappalli: "திருச்சிராப்பள்ளி",
    tirunelveli: "திருநெல்வேலி",
    tirupathur: "திருப்பத்தூர்",
    tiruppur: "திருப்பூர்",
    tiruvallur: "திருவள்ளூர்",
    tiruvannamalai: "திருவண்ணாமலை",
    tiruvarur: "திருவாரூர்",
    viluppuram: "விழுப்புரம்",
    virudhunagar: "விருதுநகர்",
    mumbai: "மும்பை",
    delhi: "டெல்லி",
    bangalore: "பெங்களூரு",
    hyderabad: "ஹைதராபாத்",
    ahmedabad: "அகமதாபாத்",
    kolkata: "கொல்கத்தா",
    surat: "சூரத்",
    jaipur: "ஜெய்ப்பூர்",
    lucknow: "லக்னோ",
    kanpur: "கான்பூர்",
    indore: "இந்தூர்",
    thane: "தானே",
    bhopal: "போபால்",
    visakhapatnam: "விசாகப்பட்டினம்",
    patna: "பாட்னா",
    vadodara: "வடோதரா",
    ghaziabad: "காசியாபாத்",
    ludhiana: "லூதியானா",
    agra: "ஆக்ரா",
    faridabad: "பரிதாபாத்",
    meerut: "மீரட்",
    rajkot: "ராஜ்கோட்",
    varanasi: "வாரணாசி",
    srinagar: "ஸ்ரீநகர்",
    aurangabad: "அவுரங்காபாத்",
    dhanbad: "தன்பாத்",
    amritsar: "அமிர்தசரஸ்",
    allahabad: "அலகாபாத்",
    howrah: "ஹவுரா",
    ranchi: "ராஞ்சி",
    gwalior: "குவாலியர்",
    jabalpur: "ஜபல்பூர்",
    vijayawada: "விஜயவாடா",
    jodhpur: "ஜோத்பூர்",
    raipur: "ராய்ப்பூர்",
    kota: "கோட்டா",
    guwahati: "கௌஹாத்தி",
    chandigarh: "சண்டிகர்",
    solapur: "சோலாப்பூர்",
    bareilly: "பரேலி",
    moradabad: "மொராதாபாத்",
    mysore: "மைசூர்",
    gurgaon: "குர்கான்",
    aligarh: "அலிகார்",
    jalandhar: "ஜலந்தர்",
    bhubaneswar: "புவனேஸ்வர்",
    thiruvananthapuram: "திருவனந்தபுரம்",
    bhiwandi: "பிவாண்டி",
    saharanpur: "சஹாரன்பூர்",
    amravati: "அமராவதி",
    bikaner: "பிகானேர்",
    noida: "நொய்டா",
    jamshedpur: "ஜாம்ஷெட்பூர்",
    bhilai: "பிலாய்",
    cuttack: "கட்டாக்",
    firozabad: "பிரோசாபாத்",
    kochi: "கொச்சி",
    nellore: "நெல்லூர்",
    bhavnagar: "பாவ்நகர்",
    dehradun: "டேராடூன்",
    durgapur: "துர்காபூர்",
    asansol: "அசன்சோல்",
    rourkela: "ரூர்கேலா",
    nanded: "நாந்தேடு",
    kolhapur: "கோலாப்பூர்",
    ajmer: "அஜ்மீர்",
    akola: "அகோலா",
    gulbarga: "குல்பர்கா",
    jamnagar: "ஜாம்நகர்",
    ujjain: "உஜ்ஜைன்",
    loni: "லோனி",
    siliguri: "சிலிகுரி",
    jhansi: "ஜான்சி",
    ulhasnagar: "உல்ஹாஸ்நகர்",
    jammu: "ஜம்மு",
    sangli: "சாங்லி",
    mangalore: "மங்களூர்",
    belgaum: "பெல்காம்",
    gaya: "கயா",
    jalgaon: "ஜல்கான்",
    udaipur: "உதய்ப்பூர்",
    shimla: "சிம்லா",
    panaji: "பனாஜி",
    imphal: "இம்பால்",
    agartala: "அகர்தலா",
    aizawl: "அய்சால்",
    kohima: "கோஹிமா",
    shillong: "ஷில்லாங்",
    itanagar: "இட்டாநகர்",
    gangtok: "கேங்டாக்",
    pondicherry: "புடுச்சேரி",
    leh: "லே",
    "port blair": "போர்ட் பிளேர்",
    silvassa: "சில்வாசா",
    daman: "தாமன்",
    kavaratti: "கவரத்தி",
  },
  hi: {
    welcome: "हार्वेस्टऑप्टिमा में आपका स्वागत है",
    tagline: "भविष्य कहनेवाला कृषि बाजार",
    farmer: "किसान",
    buyer: "संस्थागत खरीदार",
    harvest_advice: "AI कटाई सलाह",
    predicted_price: "अनुमानित मूल्य",
    market_sentiment: "बाजार की भावना",
    harvest_now: "अभी कटाई करें",
    wait_days: "{days} दिन प्रतीक्षा करें",
    place_bid: "बोली लगाएं",
    mandi_prices: "मंडी दरें",
    my_bids: "मेरी बोलियां",
    dashboard: "डैशबोर्ड",
    best_offer: "सर्वश्रेष्ठ प्रस्ताव",
    total_bids: "कुल बोलियां",
    ai_price_prediction: "AI मूल्य भविष्यवाणी",
    smart_recommendation: "स्मार्ट अनुशंसा",
    hold_price_rise: "रोकें - 2 दिनों में कीमत बढ़ेगी",
    demand_factor: "मांग कारक",
    rain_probability: "बारिश की संभावना",
    seven_day_trend: "7-दिवसीय मूल्य प्रवृत्ति",
    my_crop_listings: "मेरी फसल सूची",
    rain_alert: "बारिश की चेतावनी: आज {crop} काटने पर विचार करें",
    live: "लाइव",
    active_crops: "सक्रिय फसलें",
    pending_bids: "लंबित बोलियां",
    voice_assistant: "आवाज सहायक",
    listening: "सुन रहा है...",
    ask_me: "मुझसे कीमतों या कटाई के समय के बारे में पूछें",
    harvest_today: "आज कटाई करें",
    wait_2_days: "2 दिन प्रतीक्षा करें",
    rain_risk: "बारिश का जोखिम",
    logistics: "रसद उपलब्धता",
    nearby_buyers: "आस-पास के खरीदार",
    est_delivery: "अनुमानित वितरण समय",
    mandi_price: "वर्तमान मंडी मूल्य",
    historical_trend: "ऐतिहासिक प्रवृत्ति",
    marketplace: "बाज़ार",
    market_intelligence: "बाजार बुद्धिमत्ता",
    ai_plans: "AI कटाई योजनाएं",
    start_query: "प्रश्न शुरू करें",
    stop_ai: "AI रोकें",
    speak_now: "अब बोलें...",
    location: "स्थान",
    name: "नाम",
    role: "भूमिका",
    email: "ईमेल",
    save_profile: "प्रोफ़ाइल सहेजें",
    select_role: "भूमिका चुनें",
    enter_name: "अपना नाम दर्ज करें",
    enter_location: "अपना स्थान दर्ज करें",
    active_bids: "सक्रिय बोलियां",
    total_revenue: "कुल राजस्व",
    active_orders: "सक्रिय आदेश",
    listening_ai: "सुन रहा है...",
    logout: "लॉगआउट",
    bids: "बोलियां",
    daily: "दैनिक",
    weekly: "साप्ताहिक",
    company: "कंपनी",
    sponsor: "प्रायोजक",
    market_insights: "बाजार अंतर्दृष्टि",
    real_time_mandi: "वास्तविक समय मंडी दरें",
    timeframe: "समय सीमा",
    bid_history: "बोली इतिहास",
    no_crops: "अभी तक कोई फसल सूचीबद्ध नहीं है। अपनी पहली फसल जोड़कर शुरू करें।",
    view_ai_plan: "AI योजना देखें",
    kg_available: "किलो उपलब्ध",
    marketplace_empty: "बाज़ार वर्तमान में खाली है। बाद में फिर से जाँचें!",
    bid_placed: "बोली लगाई गई",
    bid_amount_placeholder: "प्रति किलो बोली राशि",
    list_new_crop: "नई फसल सूचीबद्ध करें",
    list_your_crop: "अपनी फसल सूचीबद्ध करें",
    crop_type: "फसल का प्रकार",
    quantity_kg: "मात्रा (किलो)",
    est_harvest: "अनुमानित फसल",
    cancel: "रद्द करें",
    list_crop: "फसल सूचीबद्ध करें",
    crop_type_placeholder: "जैसे जैविक टमाटर",
    quantity_placeholder: "500",
    location_placeholder: "जैसे वेल्लोर, तमिलनाडु",
    humidity: "नमी",
    wind: "हवा",
    ai_forecast: "AI पूर्वानुमान",
    system_healthy: "प्रणाली स्वस्थ है",
    system_degraded: "प्रणाली खराब है",
    retry_check: "प्रणाली जाँच पुन: प्रयास करें",
    details: "विवरण",
    something_went_wrong: "कुछ गलत हो गया",
    reload_app: "एप्लिकेशन पुनः लोड करें",
    enter_location_placeholder: "स्थान दर्ज करें (जैसे चेन्नई)",
    tomato: "टमाटर",
    wheat: "गेहूं",
    rice: "चावल",
    corn: "मक्का",
    potato: "आलू",
    onion: "प्याज",
    vellore: "वेल्लोर",
    chennai: "चेन्नई",
    nashik: "नासिक",
    growing: "बढ़ रहा है",
    ready: "कटाई के लिए तैयार",
    harvested: "काटा गया",
    vellore_market: "वेल्लोर बाजार",
    nashik_market: "नासिक बाजार",
    sugarcane: "गन्ना",
    turmeric: "हल्दी",
    banana: "केला",
    cotton: "कपास",
    coconut: "नारियल",
    mango: "आम",
    coffee: "कॉफी",
    tea: "चाय",
    rubber: "रबर",
    cardamom: "इलायची",
    pepper: "काली मिर्च",
    ginger: "अदरक",
    garlic: "लहसुन",
    chili: "मिर्च",
    groundnut: "मूंगफली",
    sunflower: "सूरजमुखी",
    mustard: "सरसों",
    soybean: "सोयाबीन",
    jute: "जूट",
    tobacco: "तंबाकू",
    "moong dal": "मूंग दाल",
    "urad dal": "उड़द दाल",
    "arhar dal": "अरहर दाल",
    gram: "चना",
    jowar: "ज्वार",
    bajra: "बाजरा",
    ragi: "रागी",
    barley: "जौ",
    sesame: "तिल",
    castor: "अरंडी",
    grapes: "अंगूर",
    guava: "अमरूद",
    papaya: "पपीता",
    pomegranate: "अनार",
    apple: "सेब",
    orange: "संतरा",
    coimbatore: "कोयंबटूर",
    madurai: "मदुरै",
    trichy: "त्रिची",
    pune: "पुणे",
    nagpur: "नागपुर",
    kanyakumari: "कन्याकुमारी",
    erode: "ईरोड",
    ariyalur: "अरियालुर",
    chengalpattu: "चेंगलपट्टू",
    cuddalore: "कुड्डालोर",
    dharmapuri: "धर्मपुरी",
    dindigul: "डिंडीगुल",
    kallakurichi: "कल्लाकुरिची",
    kancheepuram: "कांचीपुरम",
    karur: "करूर",
    krishnagiri: "कृष्णागिरी",
    mayiladuthurai: "मयिलादुथुराई",
    nagapattinam: "नागापट्टिनम",
    namakkal: "नामक्कल",
    nilgiris: "नीलगिरी",
    perambalur: "पेरम्बलुर",
    pudukkottai: "पुदुकोट्टई",
    ramanathapuram: "रामनाथपुरम",
    ranipet: "रानीपेट",
    salem: "सेलम",
    sivaganga: "शिवगंगा",
    tenkasi: "तेनकासी",
    thanjavur: "तंजावुर",
    theni: "थेनी",
    thoothukudi: "थूथुकुडी",
    tiruchirappalli: "तिरुचिरापल्ली",
    tirunelveli: "तिरुनेलवेली",
    tirupathur: "तिरुपाथुर",
    tiruppur: "तिरुपुर",
    tiruvallur: "तिरुवल्लूर",
    tiruvannamalai: "तिरुवन्नामलई",
    tiruvarur: "तिरुवारुर",
    viluppuram: "विलुप्पुरम",
    virudhunagar: "विरुधुनगर",
    mumbai: "मुंबई",
    delhi: "दिल्ली",
    bangalore: "बेंगलुरु",
    hyderabad: "हैदराबाद",
    ahmedabad: "अहमदाबाद",
    kolkata: "कोलकाता",
    surat: "सूरत",
    jaipur: "जयपुर",
    lucknow: "लखनऊ",
    kanpur: "कानपुर",
    indore: "इंदौर",
    thane: "ठाणे",
    bhopal: "भोपाल",
    visakhapatnam: "विशाखापत्तनम",
    patna: "पटना",
    vadodara: "वडोदरा",
    ghaziabad: "गाजियाबाद",
    ludhiana: "लुधियाना",
    agra: "आगरा",
    faridabad: "फरीदाबाद",
    meerut: "मेरठ",
    rajkot: "राजकोट",
    varanasi: "वाराणसी",
    srinagar: "श्रीनगर",
    aurangabad: "औरंगाबाद",
    dhanbad: "धनबाद",
    amritsar: "अमृतसर",
    allahabad: "इलाहाबाद",
    howrah: "हावड़ा",
    ranchi: "रांची",
    gwalior: "ग्वालियर",
    jabalpur: "जबलपुर",
    vijayawada: "विजयवाड़ा",
    jodhpur: "जोधपुर",
    raipur: "रायपुर",
    kota: "कोटा",
    guwahati: "गुवाहाटी",
    chandigarh: "चंडीगढ़",
    solapur: "सोलापुर",
    bareilly: "बरेली",
    moradabad: "मुरादाबाद",
    mysore: "मैसूर",
    gurgaon: "गुड़गांव",
    aligarh: "अलीगढ़",
    jalandhar: "जालंधर",
    bhubaneswar: "भुवनेश्वर",
    thiruvananthapuram: "तिरुवनंतपुरम",
    bhiwandi: "भिवंडी",
    saharanpur: "सहारनपुर",
    amravati: "अमरावती",
    bikaner: "बीकानेर",
    noida: "नोएडा",
    jamshedpur: "जमशेदपुर",
    bhilai: "भिलाई",
    cuttack: "कटक",
    firozabad: "फिरोजाबाद",
    kochi: "कोच्चि",
    nellore: "नेल्लोर",
    bhavnagar: "भावनगर",
    dehradun: "देहरादून",
    durgapur: "दुर्गापुर",
    asansol: "आसनसोल",
    rourkela: "राउरकेला",
    nanded: "नांदेड़",
    kolhapur: "कोल्हापुर",
    ajmer: "अजमेर",
    akola: "अकोला",
    gulbarga: "गुलबर्गा",
    jamnagar: "जामनगर",
    ujjain: "उज्जैन",
    loni: "लोनी",
    siliguri: "सिलीगुड़ी",
    jhansi: "झांसी",
    ulhasnagar: "उल्हासनगर",
    jammu: "जम्मू",
    sangli: "सांगली",
    mangalore: "मंगलौर",
    belgaum: "बेलगाम",
    gaya: "गया",
    jalgaon: "जलगांव",
    udaipur: "उदयपुर",
    shimla: "शिमला",
    panaji: "पणजी",
    imphal: "इम्फाल",
    agartala: "अगरतला",
    aizawl: "आइजोल",
    kohima: "कोहिमा",
    shillong: "शिलांग",
    itanagar: "ईटानगर",
    gangtok: "गंगटोक",
    pondicherry: "पुडुचेरी",
    leh: "लेह",
    "port blair": "पोर्ट ब्लेयर",
    silvassa: "सिलवासा",
    daman: "दमन",
    kavaratti: "कवरत्ती",
  }
};

export const CROP_TYPES = [
  "Tomato",
  "Onion",
  "Potato",
  "Rice",
  "Wheat",
  "Corn",
  "Sugarcane",
  "Turmeric",
  "Banana",
  "Cotton",
  "Coconut",
  "Mango",
  "Coffee",
  "Tea",
  "Rubber",
  "Cardamom",
  "Pepper",
  "Ginger",
  "Garlic",
  "Chili",
  "Groundnut",
  "Sunflower",
  "Mustard",
  "Soybean",
  "Jute",
  "Tobacco",
  "Moong Dal",
  "Urad Dal",
  "Arhar Dal",
  "Gram",
  "Jowar",
  "Bajra",
  "Ragi",
  "Barley",
  "Sesame",
  "Castor",
  "Grapes",
  "Guava",
  "Papaya",
  "Pomegranate",
  "Apple",
  "Orange"
];

export const LOCATIONS = [
  "Ariyalur", "Chengalpattu", "Chennai", "Coimbatore", "Cuddalore", "Dharmapuri", "Dindigul", "Erode", "Kallakurichi", "Kancheepuram", "Kanyakumari", "Karur", "Krishnagiri", "Madurai", "Mayiladuthurai", "Nagapattinam", "Namakkal", "Nilgiris", "Perambalur", "Pudukkottai", "Ramanathapuram", "Ranipet", "Salem", "Sivaganga", "Tenkasi", "Thanjavur", "Theni", "Thoothukudi", "Tiruchirappalli", "Tirunelveli", "Tirupathur", "Tiruppur", "Tiruvallur", "Tiruvannamalai", "Tiruvarur", "Vellore", "Viluppuram", "Virudhunagar",
  "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Kolkata", "Surat", "Pune", "Jaipur", "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Patna", "Vadodara", "Ghaziabad", "Ludhiana", "Agra", "Nashik", "Faridabad", "Meerut", "Rajkot", "Varanasi", "Srinagar", "Aurangabad", "Dhanbad", "Amritsar", "Allahabad", "Howrah", "Ranchi", "Gwalior", "Jabalpur", "Vijayawada", "Jodhpur", "Raipur", "Kota", "Guwahati", "Chandigarh", "Solapur", "Bareilly", "Moradabad", "Mysore", "Gurgaon", "Aligarh", "Jalandhar", "Bhubaneswar", "Thiruvananthapuram", "Bhiwandi", "Saharanpur", "Amravati", "Bikaner", "Noida", "Jamshedpur", "Bhilai", "Cuttack", "Firozabad", "Kochi", "Nellore", "Bhavnagar", "Dehradun", "Durgapur", "Asansol", "Rourkela", "Nanded", "Kolhapur", "Ajmer", "Akola", "Gulbarga", "Jamnagar", "Ujjain", "Loni", "Siliguri", "Jhansi", "Ulhasnagar", "Jammu", "Sangli", "Mangalore", "Belgaum", "Gaya", "Jalgaon", "Udaipur", "Shimla", "Panaji", "Imphal", "Agartala", "Aizawl", "Kohima", "Shillong", "Itanagar", "Gangtok", "Pondicherry", "Leh", "Port Blair", "Silvassa", "Daman", "Kavaratti"
].sort();

export const historicalMandiData = [
  { crop: "Tomato", date: "2026-03-25", price: 20, location: "Vellore" },
  { crop: "Onion", date: "2026-03-26", price: 22, location: "Vellore" },
  { crop: "Potato", date: "2026-03-27", price: 21, location: "Nashik" },
  { crop: "Rice", date: "2026-03-28", price: 25, location: "Chennai" },
  { crop: "Wheat", date: "2026-03-29", price: 24, location: "Nashik" },
];
